spring.application.name=asistencia
# 1. CONEXIoN A LA BASE DE DATOS

spring.datasource.url=jdbc:mysql://localhost:3306/db_asistencia?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

# 2. TUS CREDENCIALES
spring.datasource.username=root
spring.datasource.password=root

# 3. HIBERNATE (JPA)
# 'update': Si la tabla no existe, la crea. Si cambias la entidad Java, actualiza la tabla.
spring.jpa.hibernate.ddl-auto=update

# Esto hace que veas en la consola de IntelliJ el codigo SQL que Java esta escribiendo por ti
spring.jpa.show-sql=true

# Dialecto para MySQL 8 (o 5)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#esto muestra el mensaje de error en las pruebas
server.error.include-message=always